# Travis config file to build psycopg packages

sudo: required
dist: trusty

services:
    - docker
    - postgresql

addons:
    postgresql: 9.6

env:
    global:
        # must match the value in build_libpq.sh and build_libpq_macos.sh
        - WANT_LIBPQ="110005"

matrix:
    include:
        - env:
            SCRIPT=./scripts/build_sdist.sh
        - env:
            SCRIPT=./scripts/build_sdist.sh
            PACKAGE_NAME="psycopg2-binary"
        - addons:
                postgresql: 10
          dist: debian
          arch: arm64
          env:
            SCRIPT=./scripts/build_manylinux2014_aarch64.sh
            PACKAGE_NAME="psycopg2-binary"
        - env:
            SCRIPT=./scripts/build_manylinux1_i686.sh
            PACKAGE_NAME="psycopg2-binary"
        - env:
            SCRIPT=./scripts/build_manylinux1_x86_64.sh
            PACKAGE_NAME="psycopg2-binary"
        - os:
            osx
          osx_image:
            xcode9.2
          env:
            SCRIPT=./scripts/build_macos.sh
            PACKAGE_NAME="psycopg2-binary"

before_script:
    - sudo ./scripts/configure_postgres.sh
    - sudo chmod +x $SCRIPT

script:
- if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
     travis_wait 40 $SCRIPT;
 else
     $SCRIPT;
 fi


deploy:
  - provider: script
    script: bash scripts/upload_packages.sh
    skip_cleanup: true
    on:
      branch: master

notifications:
  email: false
